// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Info_Screen
void ui_Info_Screen_screen_init(void);
void ui_event_Info_Screen(lv_event_t * e);
lv_obj_t * ui_Info_Screen;
lv_obj_t * ui_weather;
lv_obj_t * ui_Today;
lv_obj_t * ui_TempToday;
lv_obj_t * ui_HumidBox;
lv_obj_t * ui_HumidIcon;
lv_obj_t * ui_HumidText;
lv_obj_t * ui_AQI;
lv_obj_t * ui_aqi;
lv_obj_t * ui_AQItext;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_ddmmyy;
lv_obj_t * ui_Time;
lv_obj_t * ui_tomorrow1;
lv_obj_t * ui_tomorrow2;
lv_obj_t * ui_tomorrow3;
lv_obj_t * ui_tomorrow4;
lv_obj_t * ui_tomorrow5;
lv_obj_t * ui_tomorrow6;
// CUSTOM VARIABLES


// SCREEN: ui_Menu_Screen
void ui_Menu_Screen_screen_init(void);
void ui_event_Menu_Screen(lv_event_t * e);
lv_obj_t * ui_Menu_Screen;
lv_obj_t * ui_Device1_Panel;
void ui_event_Device1_Panel_Device1_Panel_Bat_Tat_Device1(lv_event_t * e);
lv_obj_t * ui_fan_image1;
void ui_event_Light1_Panel_config(lv_event_t * e);
lv_obj_t * ui_Light1_Panel;
void ui_event_Light1_Panel_Light1_Panel_Bat_Tat_Light1(lv_event_t * e);
lv_obj_t * ui_light_image1;
lv_obj_t * ui_Device2_Panel;
void ui_event_Device2_Panel_Device2_Panel_Bat_Tat_Device2(lv_event_t * e);
lv_obj_t * ui_fan_image2;
void ui_event_Light2_Panel_config(lv_event_t * e);
lv_obj_t * ui_Light2_Panel;
void ui_event_Light2_Panel_Light2_Panel_Bat_Tat_Light2(lv_event_t * e);
lv_obj_t * ui_light_image2;
void ui_event_RGB1_Panel_config(lv_event_t * e);
lv_obj_t * ui_RGB1_Panel;
void ui_event_RGB1_Panel_RGB1_Panel_Bat_Tat_RGB1(lv_event_t * e);
lv_obj_t * ui_rgb_image1;
void ui_event_Light3_Panel_config(lv_event_t * e);
lv_obj_t * ui_Light3_Panel;
void ui_event_Light3_Panel_Light3_Panel_Bat_Tat_Light3(lv_event_t * e);
lv_obj_t * ui_light_image3;
void ui_event_Rgb2_Panel_config(lv_event_t * e);
lv_obj_t * ui_Rgb2_Panel;
void ui_event_Rgb2_Panel_Rgb2_Panel_Bat_Tat_RGB2(lv_event_t * e);
lv_obj_t * ui_rgb_image2;
void ui_event_Light_4_Panel_config(lv_event_t * e);
lv_obj_t * ui_Light_4_Panel;
void ui_event_Light_4_Panel_Light_4_Panel_Bat_Tat_Light4(lv_event_t * e);
lv_obj_t * ui_light_image_4;
// CUSTOM VARIABLES


// SCREEN: ui_RGB1_Screen
void ui_RGB1_Screen_screen_init(void);
lv_obj_t * ui_RGB1_Screen;
lv_obj_t * ui_RGB1_Color_Container;
void ui_event_RGB1_Colorwheel(lv_event_t * e);
lv_obj_t * ui_RGB1_Colorwheel;
lv_obj_t * ui_Color1_Label;
lv_obj_t * ui_RGB1_Brightness_Container;
void ui_event_RGB1_Brightness_Arc(lv_event_t * e);
lv_obj_t * ui_RGB1_Brightness_Arc;
lv_obj_t * ui_RGB1_Brightness_Label;
void ui_event_RGB1_Back(lv_event_t * e);
lv_obj_t * ui_RGB1_Back;
void ui_event_RGB1_Menu(lv_event_t * e);
lv_obj_t * ui_RGB1_Menu;
void ui_event_RGB1_Next(lv_event_t * e);
lv_obj_t * ui_RGB1_Next;
lv_obj_t * ui_RGB1_Text;
// CUSTOM VARIABLES


// SCREEN: ui_RGB2_Screen
void ui_RGB2_Screen_screen_init(void);
lv_obj_t * ui_RGB2_Screen;
lv_obj_t * ui_RGB2_Color_Container;
void ui_event_RGB2_Colorwheel(lv_event_t * e);
lv_obj_t * ui_RGB2_Colorwheel;
lv_obj_t * ui_Color2_Label;
lv_obj_t * ui_RGB2_Brightness_Container;
void ui_event_RGB2_Brightness_Arc(lv_event_t * e);
lv_obj_t * ui_RGB2_Brightness_Arc;
lv_obj_t * ui_RGB2_Brightness_Label;
void ui_event_RGB2_Back(lv_event_t * e);
lv_obj_t * ui_RGB2_Back;
void ui_event_RGB2_Menu(lv_event_t * e);
lv_obj_t * ui_RGB2_Menu;
void ui_event_RGB2_Next(lv_event_t * e);
lv_obj_t * ui_RGB2_Next;
lv_obj_t * ui_RGB2_Text;
// CUSTOM VARIABLES


// SCREEN: ui_Light1_Screen
void ui_Light1_Screen_screen_init(void);
lv_obj_t * ui_Light1_Screen;
void ui_event_Light1_Brightness_Arc(lv_event_t * e);
lv_obj_t * ui_Light1_Brightness_Arc;
lv_obj_t * ui_Brightness_Light1;
lv_obj_t * ui_Brightness_Label1;
void ui_event_Light1_Back(lv_event_t * e);
lv_obj_t * ui_Light1_Back;
void ui_event_Light1_Menu(lv_event_t * e);
lv_obj_t * ui_Light1_Menu;
void ui_event_Light1_Next(lv_event_t * e);
lv_obj_t * ui_Light1_Next;
lv_obj_t * ui_Light1_Color1;
lv_obj_t * ui_Light1_Color2;
lv_obj_t * ui_Light1_Color3;
lv_obj_t * ui_Light1_Screen_Label;
// CUSTOM VARIABLES


// SCREEN: ui_Light2_Screen
void ui_Light2_Screen_screen_init(void);
lv_obj_t * ui_Light2_Screen;
void ui_event_Light2_Brightness_Arc(lv_event_t * e);
lv_obj_t * ui_Light2_Brightness_Arc;
lv_obj_t * ui_Brightness_Light2;
lv_obj_t * ui_Brightness_Label2;
void ui_event_Light2_Back(lv_event_t * e);
lv_obj_t * ui_Light2_Back;
void ui_event_Light2_Menu(lv_event_t * e);
lv_obj_t * ui_Light2_Menu;
void ui_event_Light2_Next(lv_event_t * e);
lv_obj_t * ui_Light2_Next;
lv_obj_t * ui_Light2_Color1;
lv_obj_t * ui_Light2_Color2;
lv_obj_t * ui_Light2_Color3;
lv_obj_t * ui_Light2_Screen_Label;
// CUSTOM VARIABLES


// SCREEN: ui_Light3_Screen
void ui_Light3_Screen_screen_init(void);
lv_obj_t * ui_Light3_Screen;
void ui_event_Light3_Brightness_Arc(lv_event_t * e);
lv_obj_t * ui_Light3_Brightness_Arc;
lv_obj_t * ui_Brightness_Light3;
lv_obj_t * ui_Brightness_Label3;
void ui_event_Light3_Back(lv_event_t * e);
lv_obj_t * ui_Light3_Back;
void ui_event_Light3_Menu(lv_event_t * e);
lv_obj_t * ui_Light3_Menu;
void ui_event_Light3_Next(lv_event_t * e);
lv_obj_t * ui_Light3_Next;
lv_obj_t * ui_Light3_Color1;
lv_obj_t * ui_Light3_Color2;
lv_obj_t * ui_Light3_Color3;
lv_obj_t * ui_Light3_Screen_Label;
// CUSTOM VARIABLES


// SCREEN: ui_Light4_Screen
void ui_Light4_Screen_screen_init(void);
lv_obj_t * ui_Light4_Screen;
void ui_event_Light4_Screen1(lv_event_t * e);
lv_obj_t * ui_Light4_Brightness_Arc;
lv_obj_t * ui_Brightness_Light4;
lv_obj_t * ui_Brightness_Label4;
void ui_event_Light4_Back(lv_event_t * e);
lv_obj_t * ui_Light4_Back;
void ui_event_Light4_Menu(lv_event_t * e);
lv_obj_t * ui_Light4_Menu;
void ui_event_Light4_Next(lv_event_t * e);
lv_obj_t * ui_Light4_Next;
lv_obj_t * ui_Light4_Color1;
lv_obj_t * ui_Light4_Color2;
lv_obj_t * ui_Light4_Color3;
lv_obj_t * ui_Light4_Screen_Label;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Info_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Menu_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 200, &ui_Menu_Screen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Menu_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 200, &ui_Menu_Screen_screen_init);
    }
}

void ui_event_Menu_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Info_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 200, &ui_Info_Screen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Info_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 200, &ui_Info_Screen_screen_init);
    }
}

void ui_event_Device1_Panel_Device1_Panel_Bat_Tat_Device1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnOffDev1(e);
    }
}

void ui_event_Light1_Panel_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light1_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light1_Screen_screen_init);
    }
}

void ui_event_Light1_Panel_Light1_Panel_Bat_Tat_Light1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnOffLight1(e);
    }
}

void ui_event_Device2_Panel_Device2_Panel_Bat_Tat_Device2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnOffDev2(e);
    }
}

void ui_event_Light2_Panel_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light1_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light1_Screen_screen_init);
    }
}

void ui_event_Light2_Panel_Light2_Panel_Bat_Tat_Light2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnOffLight2(e);
    }
}

void ui_event_RGB1_Panel_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RGB1_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RGB1_Screen_screen_init);
    }
}

void ui_event_RGB1_Panel_RGB1_Panel_Bat_Tat_RGB1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnOffrgb1(e);
    }
}

void ui_event_Light3_Panel_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light3_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light3_Screen_screen_init);
    }
}

void ui_event_Light3_Panel_Light3_Panel_Bat_Tat_Light3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnOffLight3(e);
    }
}

void ui_event_Rgb2_Panel_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RGB2_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RGB2_Screen_screen_init);
    }
}

void ui_event_Rgb2_Panel_Rgb2_Panel_Bat_Tat_RGB2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnOffrgb2(e);
    }
}

void ui_event_Light_4_Panel_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light4_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light4_Screen_screen_init);
    }
}

void ui_event_Light_4_Panel_Light_4_Panel_Bat_Tat_Light4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnOffLight4(e);
    }
}

void ui_event_RGB1_Colorwheel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rgbColor1(e);
    }
}

void ui_event_RGB1_Brightness_Arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rgbBrightness1(e);
    }
}

void ui_event_RGB1_Back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RGB2_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RGB2_Screen_screen_init);
    }
}

void ui_event_RGB1_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Screen_screen_init);
    }
}

void ui_event_RGB1_Next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RGB2_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RGB2_Screen_screen_init);
    }
}

void ui_event_RGB2_Colorwheel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rgbColor1(e);
    }
}

void ui_event_RGB2_Brightness_Arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rgbBrightness1(e);
    }
}

void ui_event_RGB2_Back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RGB1_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RGB1_Screen_screen_init);
    }
}

void ui_event_RGB2_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_Screen_screen_init);
    }
}

void ui_event_RGB2_Next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RGB1_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RGB1_Screen_screen_init);
    }
}

void ui_event_Light1_Back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light4_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light4_Screen_screen_init);
    }
}

void ui_event_Light1_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Menu_Screen_screen_init);
    }
}

void ui_event_Light1_Next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light2_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light2_Screen_screen_init);
    }
}

void ui_event_Light2_Back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light1_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light1_Screen_screen_init);
    }
}

void ui_event_Light2_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Menu_Screen_screen_init);
    }
}

void ui_event_Light2_Next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light3_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light3_Screen_screen_init);
    }
}

void ui_event_Light3_Back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light2_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light2_Screen_screen_init);
    }
}

void ui_event_Light3_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Menu_Screen_screen_init);
    }
}

void ui_event_Light3_Next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light4_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light4_Screen_screen_init);
    }
}

void ui_event_Light4_Back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light3_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light3_Screen_screen_init);
    }
}

void ui_event_Light4_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Menu_Screen_screen_init);
    }
}

void ui_event_Light4_Next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light1_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Light1_Screen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Info_Screen_screen_init();
    ui_Menu_Screen_screen_init();
    ui_RGB1_Screen_screen_init();
    ui_RGB2_Screen_screen_init();
    ui_Light1_Screen_screen_init();
    ui_Light2_Screen_screen_init();
    ui_Light3_Screen_screen_init();
    ui_Light4_Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Info_Screen);
}
