// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
unsigned long lastPressTime = 0;
const unsigned long debounceDelay = 500;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_MaiTruongToiYeu;
lv_obj_t * ui_PTIT;
lv_obj_t * ui_menu;
lv_obj_t * ui_Humid_Temp;
lv_obj_t * ui_Humid_Container;
lv_obj_t * ui_humid_unit;
lv_obj_t * ui_Humid_Label;
lv_obj_t * ui_Humid_Image;
lv_obj_t * ui_Temp_Container;
lv_obj_t * ui_Symbol;
lv_obj_t * ui_Temp_Label;
lv_obj_t * ui_Temp_Image;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_Time;
lv_obj_t * ui_Hour;
lv_obj_t * ui_Dots;
lv_obj_t * ui_Min;
lv_obj_t * ui_Switch_Panel1;
void ui_event_OnOff_Button1(lv_event_t * e);
lv_obj_t * ui_OnOff_Button1;
lv_obj_t * ui_Switch_Label1;
lv_obj_t * ui_Light_Sensor;
lv_obj_t * ui_Lux_Image;
lv_obj_t * ui_Lux_Container;
lv_obj_t * ui_Lux_Label;
lv_obj_t * ui_Lux_unit;
lv_obj_t * ui_Switch_Panel2;
void ui_event_OnOff_Button2(lv_event_t * e);
lv_obj_t * ui_OnOff_Button2;
lv_obj_t * ui_Switch_Label2;
lv_obj_t * ui_Switch_Panel3;
void ui_event_OnOff_Button3(lv_event_t * e);
lv_obj_t * ui_OnOff_Button3;
lv_obj_t * ui_Switch_Label3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_OnOff_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    unsigned long currentTime = millis();  

    if (event_code == LV_EVENT_CLICKED && (currentTime - lastPressTime > debounceDelay)) {
        lastPressTime = currentTime; 
        Light1OnOff(e);
    }
}

void ui_event_OnOff_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    unsigned long currentTime = millis();  

    if (event_code == LV_EVENT_CLICKED && (currentTime - lastPressTime > debounceDelay)) {
        lastPressTime = currentTime; 
        Light2OnOff(e);
    }
}

void ui_event_OnOff_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    unsigned long currentTime = millis();  

    if (event_code == LV_EVENT_CLICKED && (currentTime - lastPressTime > debounceDelay)) {
        lastPressTime = currentTime; 
        Light3OnOff(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
