// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void FadeOff_Animation(lv_obj_t * TargetObject, int delay);
void FadeOn_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_MaiTruongToiYeu;
extern lv_obj_t * ui_PTIT;
extern lv_obj_t * ui_menu;
extern lv_obj_t * ui_Humid_Temp;
extern lv_obj_t * ui_Time_Label;
extern lv_obj_t * ui_Humid_Container;
extern lv_obj_t * ui_Humid_Label;
extern lv_obj_t * ui_Humid_Image;
extern lv_obj_t * ui_Temp_Container;
extern lv_obj_t * ui_Symbol;
extern lv_obj_t * ui_Temp_Label;
extern lv_obj_t * ui_Temp_Image;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Light_Panel1;
void ui_event_OnOff_Button1(lv_event_t * e);
extern lv_obj_t * ui_OnOff_Button1;
extern lv_obj_t * ui_Light_Label1;
extern lv_obj_t * ui_Light_OFF_Image1;
extern lv_obj_t * ui_Light_ON_Image1;
extern lv_obj_t * ui_Light_Sensor;
extern lv_obj_t * ui_Lux_Label;
extern lv_obj_t * ui_Lux_Image;
extern lv_obj_t * ui_Light_Panel2;
void ui_event_OnOff_Button2(lv_event_t * e);
extern lv_obj_t * ui_OnOff_Button2;
extern lv_obj_t * ui_Light_Label2;
extern lv_obj_t * ui_Light_OFF_Image2;
extern lv_obj_t * ui_Light_ON_Image2;
extern lv_obj_t * ui_Light_Panel3;
void ui_event_OnOff_Button3(lv_event_t * e);
extern lv_obj_t * ui_OnOff_Button3;
extern lv_obj_t * ui_Light_Label3;
extern lv_obj_t * ui_Light_OFF_Image3;
extern lv_obj_t * ui_Light_ON_Image3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1885107934);    // assets/image (1).png
LV_IMG_DECLARE(ui_img_763671598);    // assets/logo-ptit-1 (1).png
LV_IMG_DECLARE(ui_img_doam_png);    // assets/doam.png
LV_IMG_DECLARE(ui_img_nhietdo_png);    // assets/nhietdo.png
LV_IMG_DECLARE(ui_img_1305810737);    // assets/power-button (1) (1).png
LV_IMG_DECLARE(ui_img_1385634997);    // assets/light-off.png
LV_IMG_DECLARE(ui_img_light_png);    // assets/light.png
LV_IMG_DECLARE(ui_img_1836600088);    // assets/brightness (1).png

// FONTS
LV_FONT_DECLARE(ui_font_dmsans32);
LV_FONT_DECLARE(ui_font_dmsans40);
LV_FONT_DECLARE(ui_font_time);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
