// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT box

lv_obj_t * ui_box_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_box;
    cui_box = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_box, 172);
    lv_obj_set_height(cui_box, 180);
    lv_obj_set_x(cui_box, 304);
    lv_obj_set_y(cui_box, 136);
    lv_obj_set_align(cui_box, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_box, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_box, lv_color_hex(0xF4F4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_box, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_box, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_box, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(cui_box, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ImgButton1;
    cui_ImgButton1 = lv_imgbtn_create(cui_box);
    lv_obj_set_height(cui_ImgButton1, 40);
    lv_obj_set_width(cui_ImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(cui_ImgButton1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(cui_ImgButton1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_radius(cui_ImgButton1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ImgButton1, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_ImgButton1, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_ImgButton1, lv_color_hex(0x00FF07), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t * cui_object;
    cui_object = lv_label_create(cui_box);
    lv_obj_set_width(cui_object, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_object, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_object, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(cui_object, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(cui_object, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_object, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_object, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image2;
    cui_Image2 = lv_img_create(cui_box);
    lv_obj_set_width(cui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BOX_NUM);
    children[UI_COMP_BOX_BOX] = cui_box;
    children[UI_COMP_BOX_IMGBUTTON1] = cui_ImgButton1;
    children[UI_COMP_BOX_OBJECT] = cui_object;
    children[UI_COMP_BOX_IMAGE2] = cui_Image2;
    lv_obj_add_event_cb(cui_box, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_box, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_box_create_hook(cui_box);
    return cui_box;
}

