// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_CONFIG_H
#define _UI_COMP_CONFIG_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT config
#define UI_COMP_CONFIG_CONFIG 0
#define UI_COMP_CONFIG_IMGBUTTON1 1
#define UI_COMP_CONFIG_OBJECT 2
#define _UI_COMP_CONFIG_NUM 3
lv_obj_t * ui_config_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
