// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_BOX_H
#define _UI_COMP_BOX_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT box
#define UI_COMP_BOX_BOX 0
#define UI_COMP_BOX_IMGBUTTON1 1
#define UI_COMP_BOX_OBJECT 2
#define UI_COMP_BOX_IMAGE2 3
#define _UI_COMP_BOX_NUM 4
lv_obj_t * ui_box_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
