// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void OnOffDev1(lv_event_t * e)
{
	// Your code here
}

void OnOffLight1(lv_event_t * e)
{
	// Your code here
}

void OnOffDev2(lv_event_t * e)
{
	// Your code here
}

void OnOffLight2(lv_event_t * e)
{
	// Your code here
}

void OnOffrgb1(lv_event_t * e)
{
	// Your code here
}

void OnOffLight3(lv_event_t * e)
{
	// Your code here
}

void OnOffrgb2(lv_event_t * e)
{
	// Your code here
}

void OnOffLight4(lv_event_t * e)
{
	// Your code here
}

void rgbColor1(lv_event_t * e)
{
	// Your code here
}

void rgbBrightness1(lv_event_t * e)
{
	// Your code here
}
