// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_info_screen_init(void)
{
    ui_info = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_info, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_info, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_info, lv_color_hex(0x71FFF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_info, lv_color_hex(0x005A7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_info, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_info, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_obj_create(ui_info);
    lv_obj_set_width(ui_weather, 260);
    lv_obj_set_height(ui_weather, 220);
    lv_obj_set_x(ui_weather, -173);
    lv_obj_set_y(ui_weather, -78);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_weather, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Today = lv_label_create(ui_weather);
    lv_obj_set_width(ui_Today, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Today, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Today, -2);
    lv_obj_set_y(ui_Today, 0);
    lv_label_set_text(ui_Today, "Today");
    lv_obj_set_style_text_color(ui_Today, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Today, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Today, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentWeather = lv_img_create(ui_weather);
    lv_img_set_src(ui_CurrentWeather, &ui_img_sun_png);
    lv_obj_set_width(ui_CurrentWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentWeather, 0);
    lv_obj_set_y(ui_CurrentWeather, 5);
    lv_obj_set_align(ui_CurrentWeather, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_CurrentWeather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CurrentWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CurrentWeather, 255);

    ui_TempToday = lv_label_create(ui_weather);
    lv_obj_set_width(ui_TempToday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempToday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempToday, 39);
    lv_obj_set_y(ui_TempToday, -3);
    lv_obj_set_align(ui_TempToday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempToday, "35°C");
    lv_obj_set_style_text_color(ui_TempToday, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempToday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempToday, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidBox = lv_obj_create(ui_weather);
    lv_obj_remove_style_all(ui_HumidBox);
    lv_obj_set_width(ui_HumidBox, 81);
    lv_obj_set_height(ui_HumidBox, 35);
    lv_obj_set_x(ui_HumidBox, -84);
    lv_obj_set_y(ui_HumidBox, 70);
    lv_obj_set_align(ui_HumidBox, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HumidBox, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_HumidBox, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_HumidBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumidIcon = lv_img_create(ui_HumidBox);
    lv_img_set_src(ui_HumidIcon, &ui_img_1350069607);
    lv_obj_set_width(ui_HumidIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumidIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HumidIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumidText = lv_label_create(ui_HumidBox);
    lv_obj_set_width(ui_HumidText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidText, -57);
    lv_obj_set_y(ui_HumidText, 59);
    lv_obj_set_align(ui_HumidText, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HumidText, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HumidText, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_HumidText, "56%");
    lv_obj_set_style_text_color(ui_HumidText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AQI = lv_obj_create(ui_weather);
    lv_obj_remove_style_all(ui_AQI);
    lv_obj_set_width(ui_AQI, 81);
    lv_obj_set_height(ui_AQI, 35);
    lv_obj_set_x(ui_AQI, -9);
    lv_obj_set_y(ui_AQI, 70);
    lv_obj_set_align(ui_AQI, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AQI, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_AQI, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_AQI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqi = lv_img_create(ui_AQI);
    lv_img_set_src(ui_aqi, &ui_img_wind_png);
    lv_obj_set_width(ui_aqi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aqi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aqi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AQItext = lv_label_create(ui_AQI);
    lv_obj_set_width(ui_AQItext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AQItext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AQItext, -57);
    lv_obj_set_y(ui_AQItext, 59);
    lv_obj_set_align(ui_AQItext, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AQItext, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AQItext, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_AQItext, "241");
    lv_obj_set_style_text_color(ui_AQItext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AQItext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_Panel5, 260);
    lv_obj_set_height(ui_Panel5, 150);
    lv_obj_set_x(ui_Panel5, -40);
    lv_obj_set_y(ui_Panel5, -78);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddmmyy = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_ddmmyy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ddmmyy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ddmmyy, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ddmmyy, "01/01/2025");
    lv_obj_set_style_text_color(ui_ddmmyy, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddmmyy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ddmmyy, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "06:50");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow1 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_tomorrow1, 240);
    lv_obj_set_height(ui_tomorrow1, 120);
    lv_obj_set_x(ui_tomorrow1, -327);
    lv_obj_set_y(ui_tomorrow1, 176);
    lv_obj_set_align(ui_tomorrow1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow1, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date1 = lv_label_create(ui_tomorrow1);
    lv_obj_set_width(ui_date1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_date1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date1, "Tue");
    lv_obj_set_style_text_color(ui_date1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forecast1 = lv_img_create(ui_tomorrow1);
    lv_img_set_src(ui_forecast1, &ui_img_1816888194);
    lv_obj_set_width(ui_forecast1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_forecast1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_forecast1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forecast1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_forecast1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tempforecast1 = lv_label_create(ui_tomorrow1);
    lv_obj_set_width(ui_Tempforecast1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempforecast1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Tempforecast1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Tempforecast1, "25°C");
    lv_obj_set_style_text_color(ui_Tempforecast1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tempforecast1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tempforecast1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow2 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_tomorrow2, 240);
    lv_obj_set_height(ui_tomorrow2, 120);
    lv_obj_set_x(ui_tomorrow2, -201);
    lv_obj_set_y(ui_tomorrow2, 150);
    lv_obj_set_align(ui_tomorrow2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow2, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date2 = lv_label_create(ui_tomorrow2);
    lv_obj_set_width(ui_date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date2, "Fri");
    lv_obj_set_style_text_color(ui_date2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forecast2 = lv_img_create(ui_tomorrow2);
    lv_img_set_src(ui_forecast2, &ui_img_cloudnsun_png);
    lv_obj_set_width(ui_forecast2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_forecast2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_forecast2, -9);
    lv_obj_set_y(ui_forecast2, 29);
    lv_obj_set_align(ui_forecast2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forecast2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_forecast2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tempforecast2 = lv_label_create(ui_tomorrow2);
    lv_obj_set_width(ui_Tempforecast2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempforecast2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Tempforecast2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Tempforecast2, "25°C");
    lv_obj_set_style_text_color(ui_Tempforecast2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tempforecast2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tempforecast2, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow3 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_tomorrow3, 240);
    lv_obj_set_height(ui_tomorrow3, 120);
    lv_obj_set_x(ui_tomorrow3, -44);
    lv_obj_set_y(ui_tomorrow3, 150);
    lv_obj_set_align(ui_tomorrow3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow3, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date3 = lv_label_create(ui_tomorrow3);
    lv_obj_set_width(ui_date3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_date3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date3, "Wed");
    lv_obj_set_style_text_color(ui_date3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forecast3 = lv_img_create(ui_tomorrow3);
    lv_img_set_src(ui_forecast3, &ui_img_suong_png);
    lv_obj_set_width(ui_forecast3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_forecast3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_forecast3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forecast3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_forecast3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tempforecast3 = lv_label_create(ui_tomorrow3);
    lv_obj_set_width(ui_Tempforecast3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempforecast3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Tempforecast3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Tempforecast3, "25°C");
    lv_obj_set_style_text_color(ui_Tempforecast3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tempforecast3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tempforecast3, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow4 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_tomorrow4, 240);
    lv_obj_set_height(ui_tomorrow4, 120);
    lv_obj_set_x(ui_tomorrow4, 96);
    lv_obj_set_y(ui_tomorrow4, 150);
    lv_obj_set_align(ui_tomorrow4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow4, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date4 = lv_label_create(ui_tomorrow4);
    lv_obj_set_width(ui_date4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_date4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date4, "Sat");
    lv_obj_set_style_text_color(ui_date4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forecast4 = lv_img_create(ui_tomorrow4);
    lv_img_set_src(ui_forecast4, &ui_img_storm_png);
    lv_obj_set_width(ui_forecast4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_forecast4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_forecast4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forecast4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_forecast4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tempforecast4 = lv_label_create(ui_tomorrow4);
    lv_obj_set_width(ui_Tempforecast4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempforecast4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Tempforecast4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Tempforecast4, "25°C");
    lv_obj_set_style_text_color(ui_Tempforecast4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tempforecast4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tempforecast4, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow5 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_tomorrow5, 240);
    lv_obj_set_height(ui_tomorrow5, 120);
    lv_obj_set_x(ui_tomorrow5, 232);
    lv_obj_set_y(ui_tomorrow5, 150);
    lv_obj_set_align(ui_tomorrow5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow5, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date5 = lv_label_create(ui_tomorrow5);
    lv_obj_set_width(ui_date5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_date5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date5, "Thu");
    lv_obj_set_style_text_color(ui_date5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forecast5 = lv_img_create(ui_tomorrow5);
    lv_img_set_src(ui_forecast5, &ui_img_cloud_png);
    lv_obj_set_width(ui_forecast5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_forecast5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_forecast5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forecast5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_forecast5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tempforecast5 = lv_label_create(ui_tomorrow5);
    lv_obj_set_width(ui_Tempforecast5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempforecast5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Tempforecast5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Tempforecast5, "25°C");
    lv_obj_set_style_text_color(ui_Tempforecast5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tempforecast5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tempforecast5, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow6 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_tomorrow6, 240);
    lv_obj_set_height(ui_tomorrow6, 120);
    lv_obj_set_x(ui_tomorrow6, 346);
    lv_obj_set_y(ui_tomorrow6, 147);
    lv_obj_set_align(ui_tomorrow6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow6, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow6, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date6 = lv_label_create(ui_tomorrow6);
    lv_obj_set_width(ui_date6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_date6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date6, "Sun");
    lv_obj_set_style_text_color(ui_date6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forecast6 = lv_img_create(ui_tomorrow6);
    lv_img_set_src(ui_forecast6, &ui_img_rain_png);
    lv_obj_set_width(ui_forecast6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_forecast6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_forecast6, -11);
    lv_obj_set_y(ui_forecast6, -4);
    lv_obj_set_align(ui_forecast6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forecast6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_forecast6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tempforecast6 = lv_label_create(ui_tomorrow6);
    lv_obj_set_width(ui_Tempforecast6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempforecast6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Tempforecast6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Tempforecast6, "25°C");
    lv_obj_set_style_text_color(ui_Tempforecast6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tempforecast6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tempforecast6, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_info, ui_event_info, LV_EVENT_ALL, NULL);

}
