// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Info_Screen_screen_init(void)
{
    ui_Info_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Info_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Info_Screen, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Info_Screen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Info_Screen, lv_color_hex(0x71FFF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Info_Screen, lv_color_hex(0x005A7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Info_Screen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Info_Screen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_weather, 260);
    lv_obj_set_height(ui_weather, 220);
    lv_obj_set_x(ui_weather, -173);
    lv_obj_set_y(ui_weather, -78);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_weather, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Today = lv_label_create(ui_weather);
    lv_obj_set_width(ui_Today, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Today, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Today, -2);
    lv_obj_set_y(ui_Today, 0);
    lv_label_set_text(ui_Today, "Today");
    lv_obj_set_style_text_color(ui_Today, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Today, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Today, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempToday = lv_label_create(ui_weather);
    lv_obj_set_width(ui_TempToday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempToday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempToday, 39);
    lv_obj_set_y(ui_TempToday, -3);
    lv_obj_set_align(ui_TempToday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempToday, "35°C");
    lv_obj_set_style_text_color(ui_TempToday, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempToday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempToday, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidBox = lv_obj_create(ui_weather);
    lv_obj_remove_style_all(ui_HumidBox);
    lv_obj_set_width(ui_HumidBox, 81);
    lv_obj_set_height(ui_HumidBox, 35);
    lv_obj_set_x(ui_HumidBox, -84);
    lv_obj_set_y(ui_HumidBox, 70);
    lv_obj_set_align(ui_HumidBox, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HumidBox, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_HumidBox, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_HumidBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumidIcon = lv_img_create(ui_HumidBox);
    lv_img_set_src(ui_HumidIcon, &ui_img_1350069607);
    lv_obj_set_width(ui_HumidIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumidIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HumidIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumidText = lv_label_create(ui_HumidBox);
    lv_obj_set_width(ui_HumidText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidText, -57);
    lv_obj_set_y(ui_HumidText, 59);
    lv_obj_set_align(ui_HumidText, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HumidText, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HumidText, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_HumidText, "56%");
    lv_obj_set_style_text_color(ui_HumidText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AQI = lv_obj_create(ui_weather);
    lv_obj_remove_style_all(ui_AQI);
    lv_obj_set_width(ui_AQI, 81);
    lv_obj_set_height(ui_AQI, 35);
    lv_obj_set_x(ui_AQI, -9);
    lv_obj_set_y(ui_AQI, 70);
    lv_obj_set_align(ui_AQI, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AQI, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_AQI, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_AQI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqi = lv_img_create(ui_AQI);
    lv_img_set_src(ui_aqi, &ui_img_wind_png);
    lv_obj_set_width(ui_aqi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aqi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aqi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AQItext = lv_label_create(ui_AQI);
    lv_obj_set_width(ui_AQItext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AQItext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AQItext, -57);
    lv_obj_set_y(ui_AQItext, 59);
    lv_obj_set_align(ui_AQItext, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AQItext, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AQItext, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_AQItext, "241");
    lv_obj_set_style_text_color(ui_AQItext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AQItext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_Panel5, 260);
    lv_obj_set_height(ui_Panel5, 150);
    lv_obj_set_x(ui_Panel5, -40);
    lv_obj_set_y(ui_Panel5, -78);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddmmyy = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_ddmmyy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ddmmyy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ddmmyy, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ddmmyy, "01/01/2025");
    lv_obj_set_style_text_color(ui_ddmmyy, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddmmyy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ddmmyy, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "06:50");
    lv_obj_set_style_text_color(ui_Time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow1 = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_tomorrow1, 240);
    lv_obj_set_height(ui_tomorrow1, 120);
    lv_obj_set_x(ui_tomorrow1, -327);
    lv_obj_set_y(ui_tomorrow1, 176);
    lv_obj_set_align(ui_tomorrow1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow1, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow2 = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_tomorrow2, 240);
    lv_obj_set_height(ui_tomorrow2, 120);
    lv_obj_set_x(ui_tomorrow2, -201);
    lv_obj_set_y(ui_tomorrow2, 150);
    lv_obj_set_align(ui_tomorrow2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow2, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow3 = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_tomorrow3, 240);
    lv_obj_set_height(ui_tomorrow3, 120);
    lv_obj_set_x(ui_tomorrow3, -44);
    lv_obj_set_y(ui_tomorrow3, 150);
    lv_obj_set_align(ui_tomorrow3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow3, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow4 = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_tomorrow4, 240);
    lv_obj_set_height(ui_tomorrow4, 120);
    lv_obj_set_x(ui_tomorrow4, 96);
    lv_obj_set_y(ui_tomorrow4, 150);
    lv_obj_set_align(ui_tomorrow4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow4, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow5 = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_tomorrow5, 240);
    lv_obj_set_height(ui_tomorrow5, 120);
    lv_obj_set_x(ui_tomorrow5, 232);
    lv_obj_set_y(ui_tomorrow5, 150);
    lv_obj_set_align(ui_tomorrow5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow5, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow6 = lv_obj_create(ui_Info_Screen);
    lv_obj_set_width(ui_tomorrow6, 240);
    lv_obj_set_height(ui_tomorrow6, 120);
    lv_obj_set_x(ui_tomorrow6, 346);
    lv_obj_set_y(ui_tomorrow6, 147);
    lv_obj_set_align(ui_tomorrow6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tomorrow6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow6, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tomorrow6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tomorrow6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tomorrow6, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tomorrow6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tomorrow6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Info_Screen, ui_event_Info_Screen, LV_EVENT_ALL, NULL);

}
