// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Light2_Screen_screen_init(void)
{
    ui_Light2_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Light2_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Light2_Screen, lv_color_hex(0xFFD72C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light2_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Light2_Screen, lv_color_hex(0xFF7500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Light2_Screen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light2_Brightness_Arc = lv_arc_create(ui_Light2_Screen);
    lv_obj_set_width(ui_Light2_Brightness_Arc, 200);
    lv_obj_set_height(ui_Light2_Brightness_Arc, 200);
    lv_obj_set_x(ui_Light2_Brightness_Arc, 0);
    lv_obj_set_y(ui_Light2_Brightness_Arc, -50);
    lv_obj_set_align(ui_Light2_Brightness_Arc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Light2_Brightness_Arc, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_arc_set_value(ui_Light2_Brightness_Arc, 0);
    lv_arc_set_bg_angles(ui_Light2_Brightness_Arc, 110, 70);

    lv_obj_set_style_arc_color(ui_Light2_Brightness_Arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Light2_Brightness_Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Light2_Brightness_Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light2_Brightness_Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Brightness_Light2 = lv_label_create(ui_Light2_Screen);
    lv_obj_set_width(ui_Brightness_Light2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brightness_Light2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Brightness_Light2, 0);
    lv_obj_set_y(ui_Brightness_Light2, -65);
    lv_obj_set_align(ui_Brightness_Light2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brightness_Light2, "0%");
    lv_obj_add_flag(ui_Brightness_Light2, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_font(ui_Brightness_Light2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brightness_Label2 = lv_label_create(ui_Light2_Screen);
    lv_obj_set_width(ui_Brightness_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brightness_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Brightness_Label2, 0);
    lv_obj_set_y(ui_Brightness_Label2, -25);
    lv_obj_set_align(ui_Brightness_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brightness_Label2, "Brightness");
    lv_obj_add_flag(ui_Brightness_Label2, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_font(ui_Brightness_Label2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light2_Back = lv_imgbtn_create(ui_Light2_Screen);
    lv_imgbtn_set_src(ui_Light2_Back, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2001105536, NULL);
    lv_imgbtn_set_src(ui_Light2_Back, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2001105536, NULL);
    lv_imgbtn_set_src(ui_Light2_Back, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_2001105536, NULL);
    lv_obj_set_width(ui_Light2_Back, 50);
    lv_obj_set_height(ui_Light2_Back, 50);
    lv_obj_set_x(ui_Light2_Back, 0);
    lv_obj_set_y(ui_Light2_Back, -5);
    lv_obj_set_align(ui_Light2_Back, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Light2_Back, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_radius(ui_Light2_Back, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Light2_Back, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Light2_Back, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Light2_Menu = lv_imgbtn_create(ui_Light2_Screen);
    lv_imgbtn_set_src(ui_Light2_Menu, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1987010666, NULL);
    lv_imgbtn_set_src(ui_Light2_Menu, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1987010666, NULL);
    lv_obj_set_width(ui_Light2_Menu, 60);
    lv_obj_set_height(ui_Light2_Menu, 60);
    lv_obj_set_align(ui_Light2_Menu, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Light2_Menu, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_radius(ui_Light2_Menu, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Light2_Menu, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Light2_Menu, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Light2_Next = lv_imgbtn_create(ui_Light2_Screen);
    lv_imgbtn_set_src(ui_Light2_Next, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_115668498, NULL);
    lv_imgbtn_set_src(ui_Light2_Next, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_115668498, NULL);
    lv_obj_set_width(ui_Light2_Next, 50);
    lv_obj_set_height(ui_Light2_Next, 50);
    lv_obj_set_x(ui_Light2_Next, 0);
    lv_obj_set_y(ui_Light2_Next, -5);
    lv_obj_set_align(ui_Light2_Next, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Light2_Next, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_radius(ui_Light2_Next, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Light2_Next, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Light2_Next, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Light2_Color1 = lv_btn_create(ui_Light2_Screen);
    lv_obj_set_width(ui_Light2_Color1, 50);
    lv_obj_set_height(ui_Light2_Color1, 50);
    lv_obj_set_x(ui_Light2_Color1, -180);
    lv_obj_set_y(ui_Light2_Color1, 110);
    lv_obj_set_align(ui_Light2_Color1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Light2_Color1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Light2_Color1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Light2_Color1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Light2_Color1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light2_Color1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Light2_Color1, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Light2_Color1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Light2_Color1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light2_Color2 = lv_btn_create(ui_Light2_Screen);
    lv_obj_set_width(ui_Light2_Color2, 50);
    lv_obj_set_height(ui_Light2_Color2, 50);
    lv_obj_set_x(ui_Light2_Color2, 0);
    lv_obj_set_y(ui_Light2_Color2, 110);
    lv_obj_set_align(ui_Light2_Color2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Light2_Color2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Light2_Color2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Light2_Color2, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Light2_Color2, lv_color_hex(0xFFE300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light2_Color2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Light2_Color2, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Light2_Color2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Light2_Color2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light2_Color3 = lv_btn_create(ui_Light2_Screen);
    lv_obj_set_width(ui_Light2_Color3, 50);
    lv_obj_set_height(ui_Light2_Color3, 50);
    lv_obj_set_x(ui_Light2_Color3, 180);
    lv_obj_set_y(ui_Light2_Color3, 110);
    lv_obj_set_align(ui_Light2_Color3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Light2_Color3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Light2_Color3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Light2_Color3, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Light2_Color3, lv_color_hex(0xFF9600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light2_Color3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Light2_Color3, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Light2_Color3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Light2_Color3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light2_Screen_Label = lv_label_create(ui_Light2_Screen);
    lv_obj_set_width(ui_Light2_Screen_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Light2_Screen_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Light2_Screen_Label, 0);
    lv_obj_set_y(ui_Light2_Screen_Label, -190);
    lv_obj_set_align(ui_Light2_Screen_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Light2_Screen_Label, "Light 2");
    lv_obj_set_style_text_font(ui_Light2_Screen_Label, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Light2_Brightness_Arc, ui_event_Light2_Brightness_Arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Light2_Back, ui_event_Light2_Back, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Light2_Menu, ui_event_Light2_Menu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Light2_Next, ui_event_Light2_Next, LV_EVENT_ALL, NULL);

}
