// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_home
void ui_home_screen_init(void);
void ui_event_home(lv_event_t * e);
lv_obj_t * ui_home;
// CUSTOM VARIABLES


// SCREEN: ui_info
void ui_info_screen_init(void);
void ui_event_info(lv_event_t * e);
lv_obj_t * ui_info;
lv_obj_t * ui_Calendar;
lv_obj_t * ui_Clock;
lv_obj_t * ui_Time;
lv_obj_t * ui_ddmmyy;
lv_obj_t * ui_DMY;
lv_obj_t * ui_Inside;
lv_obj_t * ui_INhome;
lv_obj_t * ui_Temp1;
lv_obj_t * ui_Humid1;
lv_obj_t * ui_Weather;
lv_obj_t * ui_Moonphase;
lv_obj_t * ui_moon;
lv_obj_t * ui_state;
lv_obj_t * ui_rain_meter;
lv_obj_t * ui_Rain;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_Outside;
lv_obj_t * ui_OUThome;
lv_obj_t * ui_Temp2;
lv_obj_t * ui_Humid2;
lv_obj_t * ui_line;
// CUSTOM VARIABLES


// SCREEN: ui_menu
void ui_menu_screen_init(void);
void ui_event_menu(lv_event_t * e);
lv_obj_t * ui_menu;
lv_obj_t * ui_device1;
void ui_event_device1_ImgButton1(lv_event_t * e);
void ui_event_light1_config(lv_event_t * e);
lv_obj_t * ui_light1;
void ui_event_light1_light1_ImgButton2(lv_event_t * e);
lv_obj_t * ui_device2;
void ui_event_device2_device2_ImgButton3(lv_event_t * e);
void ui_event_light2_config(lv_event_t * e);
lv_obj_t * ui_light2;
void ui_event_light2_light2_ImgButton4(lv_event_t * e);
void ui_event_rgb3_config(lv_event_t * e);
lv_obj_t * ui_rgb3;
void ui_event_rgb3_rgb3_ImgButton5(lv_event_t * e);
void ui_event_light3_config(lv_event_t * e);
lv_obj_t * ui_light3;
void ui_event_light3_light3_ImgButton6(lv_event_t * e);
void ui_event_rgb4_config(lv_event_t * e);
lv_obj_t * ui_rgb4;
void ui_event_rgb4_rgb4_ImgButton7(lv_event_t * e);
void ui_event_light4_config(lv_event_t * e);
lv_obj_t * ui_light4;
void ui_event_light4_light4_ImgButton8(lv_event_t * e);
// CUSTOM VARIABLES


// SCREEN: ui_rgb1
void ui_rgb1_screen_init(void);
void ui_event_rgb1(lv_event_t * e);
lv_obj_t * ui_rgb1;
lv_obj_t * ui_RGB11;
void ui_event_Colorwheel1(lv_event_t * e);
lv_obj_t * ui_Colorwheel1;
lv_obj_t * ui_rgbcolor1;
lv_obj_t * ui_RGB12;
void ui_event_Brightness1(lv_event_t * e);
lv_obj_t * ui_Brightness1;
lv_obj_t * ui_rgbbrightness1;
// CUSTOM VARIABLES


// SCREEN: ui_rgb2
void ui_rgb2_screen_init(void);
void ui_event_rgb2(lv_event_t * e);
lv_obj_t * ui_rgb2;
lv_obj_t * ui_RGB21;
void ui_event_Colorwheel2(lv_event_t * e);
lv_obj_t * ui_Colorwheel2;
lv_obj_t * ui_rgbcolor2;
lv_obj_t * ui_RGB22;
void ui_event_Brightness2(lv_event_t * e);
lv_obj_t * ui_Brightness2;
lv_obj_t * ui_rgbbrightness2;
// CUSTOM VARIABLES


// SCREEN: ui_Light1
void ui_Light1_screen_init(void);
void ui_event_Light1(lv_event_t * e);
lv_obj_t * ui_Light1;
lv_obj_t * ui_light11;
lv_obj_t * ui_mau1;
void ui_event_mau11(lv_event_t * e);
lv_obj_t * ui_mau11;
lv_obj_t * ui_light12;
lv_obj_t * ui_dosang1;
void ui_event_dosang11(lv_event_t * e);
lv_obj_t * ui_dosang11;
// CUSTOM VARIABLES


// SCREEN: ui_Light2
void ui_Light2_screen_init(void);
void ui_event_Light2(lv_event_t * e);
lv_obj_t * ui_Light2;
lv_obj_t * ui_light21;
lv_obj_t * ui_mau2;
void ui_event_mau21(lv_event_t * e);
lv_obj_t * ui_mau21;
lv_obj_t * ui_light22;
lv_obj_t * ui_dosang2;
void ui_event_dosang21(lv_event_t * e);
lv_obj_t * ui_dosang21;
// CUSTOM VARIABLES


// SCREEN: ui_Light3
void ui_Light3_screen_init(void);
void ui_event_Light3(lv_event_t * e);
lv_obj_t * ui_Light3;
lv_obj_t * ui_light31;
lv_obj_t * ui_mau3;
void ui_event_mau31(lv_event_t * e);
lv_obj_t * ui_mau31;
lv_obj_t * ui_light32;
lv_obj_t * ui_dosang3;
void ui_event_dosang31(lv_event_t * e);
lv_obj_t * ui_dosang31;
// CUSTOM VARIABLES


// SCREEN: ui_Light4
void ui_Light4_screen_init(void);
void ui_event_Light4(lv_event_t * e);
lv_obj_t * ui_Light4;
lv_obj_t * ui_light41;
lv_obj_t * ui_mau4;
void ui_event_mau41(lv_event_t * e);
lv_obj_t * ui_mau41;
lv_obj_t * ui_light42;
lv_obj_t * ui_dosang4;
void ui_event_dosang41(lv_event_t * e);
lv_obj_t * ui_dosang41;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_[1] = {&ui_img_1205843_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_menu_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_info, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_info_screen_init);
    }
}

void ui_event_info(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_home_screen_init);
    }
}

void ui_event_menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_home_screen_init);
    }
}

void ui_event_device1_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        device1ON(e);
    }
}

void ui_event_light1_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Light1_screen_init);
    }
}

void ui_event_light1_light1_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        light1ON(e);
    }
}

void ui_event_device2_device2_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        device2ON(e);
    }
}

void ui_event_light2_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Light1_screen_init);
    }
}

void ui_event_light2_light2_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        light2ON(e);
    }
}

void ui_event_rgb3_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_rgb1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_rgb1_screen_init);
    }
}

void ui_event_rgb3_rgb3_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        turnONrgb1(e);
    }
}

void ui_event_light3_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Light3_screen_init);
    }
}

void ui_event_light3_light3_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        light3ON(e);
    }
}

void ui_event_rgb4_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_rgb2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_rgb2_screen_init);
    }
}

void ui_event_rgb4_rgb4_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        turnONrgb2(e);
    }
}

void ui_event_light4_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light4, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Light4_screen_init);
    }
}

void ui_event_light4_light4_ImgButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lightON8(e);
    }
}

void ui_event_rgb1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_menu_screen_init);
    }
}

void ui_event_Colorwheel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rgbColor1(e);
    }
}

void ui_event_Brightness1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rgbBrightness1(e);
    }
}

void ui_event_rgb2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_menu_screen_init);
    }
}

void ui_event_Colorwheel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rgbColor2(e);
    }
}

void ui_event_Brightness2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rgbBrightness2(e);
    }
}

void ui_event_Light1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_menu_screen_init);
    }
}

void ui_event_mau11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        thaymaul1(e);
    }
}

void ui_event_dosang11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        thaydosangl1(e);
    }
}

void ui_event_Light2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_menu_screen_init);
    }
}

void ui_event_mau21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        thaymaul2(e);
    }
}

void ui_event_dosang21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        thaydosangl2(e);
    }
}

void ui_event_Light3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_menu_screen_init);
    }
}

void ui_event_mau31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        thaymaul3(e);
    }
}

void ui_event_dosang31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        thaydosangl3(e);
    }
}

void ui_event_Light4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_menu_screen_init);
    }
}

void ui_event_mau41(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        thaymaul4(e);
    }
}

void ui_event_dosang41(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        thaydosangl4(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_home_screen_init();
    ui_info_screen_init();
    ui_menu_screen_init();
    ui_rgb1_screen_init();
    ui_rgb2_screen_init();
    ui_Light1_screen_init();
    ui_Light2_screen_init();
    ui_Light3_screen_init();
    ui_Light4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_home);
}
