// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_home
void ui_home_screen_init(void);
void ui_event_home(lv_event_t * e);
extern lv_obj_t * ui_home;
// CUSTOM VARIABLES

// SCREEN: ui_info
void ui_info_screen_init(void);
void ui_event_info(lv_event_t * e);
extern lv_obj_t * ui_info;
extern lv_obj_t * ui_Calendar;
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_ddmmyy;
extern lv_obj_t * ui_DMY;
extern lv_obj_t * ui_Inside;
extern lv_obj_t * ui_INhome;
extern lv_obj_t * ui_Temp1;
extern lv_obj_t * ui_Humid1;
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_Moonphase;
extern lv_obj_t * ui_moon;
extern lv_obj_t * ui_state;
extern lv_obj_t * ui_rain_meter;
extern lv_obj_t * ui_Rain;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Outside;
extern lv_obj_t * ui_OUThome;
extern lv_obj_t * ui_Temp2;
extern lv_obj_t * ui_Humid2;
extern lv_obj_t * ui_line;
// CUSTOM VARIABLES

// SCREEN: ui_menu
void ui_menu_screen_init(void);
void ui_event_menu(lv_event_t * e);
extern lv_obj_t * ui_menu;
extern lv_obj_t * ui_device1;
void ui_event_light1_config(lv_event_t * e);
extern lv_obj_t * ui_light1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_device2;
void ui_event_light2_config(lv_event_t * e);
extern lv_obj_t * ui_light2;
extern lv_obj_t * ui_Image3;
void ui_event_rgb3_config(lv_event_t * e);
extern lv_obj_t * ui_rgb3;
void ui_event_light3_config(lv_event_t * e);
extern lv_obj_t * ui_light3;
extern lv_obj_t * ui_Image2;
void ui_event_rgb4_config(lv_event_t * e);
extern lv_obj_t * ui_rgb4;
void ui_event_light4_config(lv_event_t * e);
extern lv_obj_t * ui_light4;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_rgb1
void ui_rgb1_screen_init(void);
void ui_event_rgb1(lv_event_t * e);
extern lv_obj_t * ui_rgb1;
extern lv_obj_t * ui_RGB11;
void ui_event_Colorwheel1(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel1;
extern lv_obj_t * ui_rgbcolor1;
extern lv_obj_t * ui_RGB12;
void ui_event_Brightness1(lv_event_t * e);
extern lv_obj_t * ui_Brightness1;
extern lv_obj_t * ui_rgbbrightness1;
// CUSTOM VARIABLES

// SCREEN: ui_rgb2
void ui_rgb2_screen_init(void);
void ui_event_rgb2(lv_event_t * e);
extern lv_obj_t * ui_rgb2;
extern lv_obj_t * ui_RGB21;
void ui_event_Colorwheel2(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel2;
extern lv_obj_t * ui_rgbcolor2;
extern lv_obj_t * ui_RGB22;
void ui_event_Brightness2(lv_event_t * e);
extern lv_obj_t * ui_Brightness2;
extern lv_obj_t * ui_rgbbrightness2;
// CUSTOM VARIABLES

// SCREEN: ui_Light1
void ui_Light1_screen_init(void);
extern lv_obj_t * ui_Light1;
void ui_event_chinhdosang(lv_event_t * e);
extern lv_obj_t * ui_chinhdosang;
extern lv_obj_t * ui_dosang;
extern lv_obj_t * ui_Label5;
void ui_event_before1(lv_event_t * e);
extern lv_obj_t * ui_before1;
void ui_event_menu1(lv_event_t * e);
extern lv_obj_t * ui_menu1;
void ui_event_next1(lv_event_t * e);
extern lv_obj_t * ui_next1;
extern lv_obj_t * ui_mau1;
extern lv_obj_t * ui_mau2;
extern lv_obj_t * ui_mau3;
extern lv_obj_t * ui_LIGHT1;
// CUSTOM VARIABLES

// SCREEN: ui_Light2
void ui_Light2_screen_init(void);
extern lv_obj_t * ui_Light2;
void ui_event_chinhdosang1(lv_event_t * e);
extern lv_obj_t * ui_chinhdosang1;
extern lv_obj_t * ui_dosang1;
extern lv_obj_t * ui_Label6;
void ui_event_before2(lv_event_t * e);
extern lv_obj_t * ui_before2;
void ui_event_menu2(lv_event_t * e);
extern lv_obj_t * ui_menu2;
void ui_event_next2(lv_event_t * e);
extern lv_obj_t * ui_next2;
extern lv_obj_t * ui_mau4;
extern lv_obj_t * ui_mau5;
extern lv_obj_t * ui_mau6;
extern lv_obj_t * ui_LIGHT2;
// CUSTOM VARIABLES

// SCREEN: ui_Light3
void ui_Light3_screen_init(void);
extern lv_obj_t * ui_Light3;
void ui_event_chinhdosang2(lv_event_t * e);
extern lv_obj_t * ui_chinhdosang2;
extern lv_obj_t * ui_dosang2;
extern lv_obj_t * ui_Label7;
void ui_event_before3(lv_event_t * e);
extern lv_obj_t * ui_before3;
void ui_event_menu3(lv_event_t * e);
extern lv_obj_t * ui_menu3;
void ui_event_next3(lv_event_t * e);
extern lv_obj_t * ui_next3;
extern lv_obj_t * ui_mau7;
extern lv_obj_t * ui_mau8;
extern lv_obj_t * ui_mau9;
extern lv_obj_t * ui_LIGHT3;
// CUSTOM VARIABLES

// SCREEN: ui_Light4
void ui_Light4_screen_init(void);
extern lv_obj_t * ui_Light4;
void ui_event_chinhdosang3(lv_event_t * e);
extern lv_obj_t * ui_chinhdosang3;
extern lv_obj_t * ui_dosang3;
extern lv_obj_t * ui_Label8;
void ui_event_before4(lv_event_t * e);
extern lv_obj_t * ui_before4;
void ui_event_menu4(lv_event_t * e);
extern lv_obj_t * ui_menu4;
void ui_event_next4(lv_event_t * e);
extern lv_obj_t * ui_next4;
extern lv_obj_t * ui_mau10;
extern lv_obj_t * ui_mau11;
extern lv_obj_t * ui_mau12;
extern lv_obj_t * ui_LIGHT4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1590078891);    // assets/GettyImages-9261821821-5c69c1b7c9e77c0001675a49.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_clouds_png);    // assets/clouds.png
LV_IMG_DECLARE(ui_img_moon_png);    // assets/moon.png
LV_IMG_DECLARE(ui_img_719384);    // assets/power-button (2).png
LV_IMG_DECLARE(ui_img_276569025);    // assets/light-bulb (1).png
LV_IMG_DECLARE(ui_img_2001105536);    // assets/back (1).png
LV_IMG_DECLARE(ui_img_1987010666);    // assets/more (1).png
LV_IMG_DECLARE(ui_img_115668498);    // assets/next (1).png

// FONTS
LV_FONT_DECLARE(ui_font_bonus);
LV_FONT_DECLARE(ui_font_digi40);
LV_FONT_DECLARE(ui_font_digital);
LV_FONT_DECLARE(ui_font_digital60);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
