// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_home
void ui_home_screen_init(void);
void ui_event_home(lv_event_t * e);
extern lv_obj_t * ui_home;
// CUSTOM VARIABLES

// SCREEN: ui_info
void ui_info_screen_init(void);
void ui_event_info(lv_event_t * e);
extern lv_obj_t * ui_info;
extern lv_obj_t * ui_Calendar;
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_ddmmyy;
extern lv_obj_t * ui_DMY;
extern lv_obj_t * ui_Inside;
extern lv_obj_t * ui_INhome;
extern lv_obj_t * ui_Temp1;
extern lv_obj_t * ui_Humid1;
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_Moonphase;
extern lv_obj_t * ui_moon;
extern lv_obj_t * ui_state;
extern lv_obj_t * ui_rain_meter;
extern lv_obj_t * ui_Rain;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Outside;
extern lv_obj_t * ui_OUThome;
extern lv_obj_t * ui_Temp2;
extern lv_obj_t * ui_Humid2;
extern lv_obj_t * ui_line;
// CUSTOM VARIABLES

// SCREEN: ui_menu
void ui_menu_screen_init(void);
void ui_event_menu(lv_event_t * e);
extern lv_obj_t * ui_menu;
extern lv_obj_t * ui_device1;
void ui_event_device1_ImgButton1(lv_event_t * e);
void ui_event_light1_config(lv_event_t * e);
extern lv_obj_t * ui_light1;
void ui_event_light1_light1_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_device2;
void ui_event_device2_device2_ImgButton3(lv_event_t * e);
void ui_event_light2_config(lv_event_t * e);
extern lv_obj_t * ui_light2;
void ui_event_light2_light2_ImgButton4(lv_event_t * e);
void ui_event_rgb3_config(lv_event_t * e);
extern lv_obj_t * ui_rgb3;
void ui_event_rgb3_rgb3_ImgButton5(lv_event_t * e);
void ui_event_light3_config(lv_event_t * e);
extern lv_obj_t * ui_light3;
void ui_event_light3_light3_ImgButton6(lv_event_t * e);
void ui_event_rgb4_config(lv_event_t * e);
extern lv_obj_t * ui_rgb4;
void ui_event_rgb4_rgb4_ImgButton7(lv_event_t * e);
void ui_event_light4_config(lv_event_t * e);
extern lv_obj_t * ui_light4;
void ui_event_light4_light4_ImgButton8(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_rgb1
void ui_rgb1_screen_init(void);
void ui_event_rgb1(lv_event_t * e);
extern lv_obj_t * ui_rgb1;
extern lv_obj_t * ui_RGB11;
void ui_event_Colorwheel1(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel1;
extern lv_obj_t * ui_rgbcolor1;
extern lv_obj_t * ui_RGB12;
void ui_event_Brightness1(lv_event_t * e);
extern lv_obj_t * ui_Brightness1;
extern lv_obj_t * ui_rgbbrightness1;
// CUSTOM VARIABLES

// SCREEN: ui_rgb2
void ui_rgb2_screen_init(void);
void ui_event_rgb2(lv_event_t * e);
extern lv_obj_t * ui_rgb2;
extern lv_obj_t * ui_RGB21;
void ui_event_Colorwheel2(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel2;
extern lv_obj_t * ui_rgbcolor2;
extern lv_obj_t * ui_RGB22;
void ui_event_Brightness2(lv_event_t * e);
extern lv_obj_t * ui_Brightness2;
extern lv_obj_t * ui_rgbbrightness2;
// CUSTOM VARIABLES

// SCREEN: ui_Light1
void ui_Light1_screen_init(void);
void ui_event_Light1(lv_event_t * e);
extern lv_obj_t * ui_Light1;
extern lv_obj_t * ui_light11;
extern lv_obj_t * ui_mau1;
void ui_event_mau11(lv_event_t * e);
extern lv_obj_t * ui_mau11;
extern lv_obj_t * ui_light12;
extern lv_obj_t * ui_dosang1;
void ui_event_dosang11(lv_event_t * e);
extern lv_obj_t * ui_dosang11;
// CUSTOM VARIABLES

// SCREEN: ui_Light2
void ui_Light2_screen_init(void);
void ui_event_Light2(lv_event_t * e);
extern lv_obj_t * ui_Light2;
extern lv_obj_t * ui_light21;
extern lv_obj_t * ui_mau2;
void ui_event_mau21(lv_event_t * e);
extern lv_obj_t * ui_mau21;
extern lv_obj_t * ui_light22;
extern lv_obj_t * ui_dosang2;
void ui_event_dosang21(lv_event_t * e);
extern lv_obj_t * ui_dosang21;
// CUSTOM VARIABLES

// SCREEN: ui_Light3
void ui_Light3_screen_init(void);
void ui_event_Light3(lv_event_t * e);
extern lv_obj_t * ui_Light3;
extern lv_obj_t * ui_light31;
extern lv_obj_t * ui_mau3;
void ui_event_mau31(lv_event_t * e);
extern lv_obj_t * ui_mau31;
extern lv_obj_t * ui_light32;
extern lv_obj_t * ui_dosang3;
void ui_event_dosang31(lv_event_t * e);
extern lv_obj_t * ui_dosang31;
// CUSTOM VARIABLES

// SCREEN: ui_Light4
void ui_Light4_screen_init(void);
void ui_event_Light4(lv_event_t * e);
extern lv_obj_t * ui_Light4;
extern lv_obj_t * ui_light41;
extern lv_obj_t * ui_mau4;
void ui_event_mau41(lv_event_t * e);
extern lv_obj_t * ui_mau41;
extern lv_obj_t * ui_light42;
extern lv_obj_t * ui_dosang4;
void ui_event_dosang41(lv_event_t * e);
extern lv_obj_t * ui_dosang41;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1205843_png);    // assets/1205843.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_clouds_png);    // assets/clouds.png
LV_IMG_DECLARE(ui_img_moon_png);    // assets/moon.png
LV_IMG_DECLARE(ui_img_2088635469);    // assets/power-switch.png

// FONTS
LV_FONT_DECLARE(ui_font_bonus);
LV_FONT_DECLARE(ui_font_digi40);
LV_FONT_DECLARE(ui_font_digital);
LV_FONT_DECLARE(ui_font_digital60);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
