// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT config

lv_obj_t * ui_config_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_config;
    cui_config = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_config, 180);
    lv_obj_set_height(cui_config, 200);
    lv_obj_set_align(cui_config, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_config, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_config, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(cui_config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_config, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_config, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ImgButton1;
    cui_ImgButton1 = lv_imgbtn_create(cui_config);
    lv_imgbtn_set_src(cui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2088635469, NULL);
    lv_imgbtn_set_src(cui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2088635469, NULL);
    lv_imgbtn_set_src(cui_ImgButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_2088635469, NULL);
    lv_imgbtn_set_src(cui_ImgButton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_2088635469, NULL);
    lv_imgbtn_set_src(cui_ImgButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_2088635469, NULL);
    lv_imgbtn_set_src(cui_ImgButton1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_2088635469, NULL);
    lv_obj_set_height(cui_ImgButton1, 64);
    lv_obj_set_width(cui_ImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(cui_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ImgButton1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(cui_ImgButton1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ImgButton1, lv_color_hex(0xE60000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_ImgButton1, 50, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_ImgButton1, lv_color_hex(0x01E800), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(cui_ImgButton1, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(cui_ImgButton1, lv_color_hex(0xE60000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_radius(cui_ImgButton1, 50, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_config);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(cui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONFIG_NUM);
    children[UI_COMP_CONFIG_CONFIG] = cui_config;
    children[UI_COMP_CONFIG_IMGBUTTON1] = cui_ImgButton1;
    children[UI_COMP_CONFIG_LABEL1] = cui_Label1;
    lv_obj_add_event_cb(cui_config, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_config, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_config_create_hook(cui_config);
    return cui_config;
}

