// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void device1ON(lv_event_t * e);
void light1ON(lv_event_t * e);
void device2ON(lv_event_t * e);
void light2ON(lv_event_t * e);
void turnONrgb1(lv_event_t * e);
void light3ON(lv_event_t * e);
void turnONrgb2(lv_event_t * e);
void lightON8(lv_event_t * e);
void rgbColor1(lv_event_t * e);
void rgbBrightness1(lv_event_t * e);
void rgbColor2(lv_event_t * e);
void rgbBrightness2(lv_event_t * e);
void thaymaul1(lv_event_t * e);
void thaydosangl1(lv_event_t * e);
void thaymaul2(lv_event_t * e);
void thaydosangl2(lv_event_t * e);
void thaymaul3(lv_event_t * e);
void thaydosangl3(lv_event_t * e);
void thaymaul4(lv_event_t * e);
void thaydosangl4(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
