// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void device1ON(lv_event_t * e)
{
	// Your code here
}

void light1ON(lv_event_t * e)
{
	// Your code here
}

void device2ON(lv_event_t * e)
{
	// Your code here
}

void light2ON(lv_event_t * e)
{
	// Your code here
}

void turnONrgb1(lv_event_t * e)
{
	// Your code here
}

void light3ON(lv_event_t * e)
{
	// Your code here
}

void turnONrgb2(lv_event_t * e)
{
	// Your code here
}

void lightON8(lv_event_t * e)
{
	// Your code here
}

void rgbColor1(lv_event_t * e)
{
	// Your code here
}

void rgbBrightness1(lv_event_t * e)
{
	// Your code here
}

void rgbColor2(lv_event_t * e)
{
	// Your code here
}

void rgbBrightness2(lv_event_t * e)
{
	// Your code here
}

void thaymaul1(lv_event_t * e)
{
	// Your code here
}

void thaydosangl1(lv_event_t * e)
{
	// Your code here
}

void thaymaul2(lv_event_t * e)
{
	// Your code here
}

void thaydosangl2(lv_event_t * e)
{
	// Your code here
}

void thaymaul3(lv_event_t * e)
{
	// Your code here
}

void thaydosangl3(lv_event_t * e)
{
	// Your code here
}

void thaymaul4(lv_event_t * e)
{
	// Your code here
}

void thaydosangl4(lv_event_t * e)
{
	// Your code here
}
