// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void rgbColor1(lv_event_t * e);
void rgbBrightness1(lv_event_t * e);
void rgbColor2(lv_event_t * e);
void rgbBrightness2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
