// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_info_screen_init(void)
{
    ui_info = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_info, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_info, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);

    ui_Calendar = lv_obj_create(ui_info);
    lv_obj_remove_style_all(ui_Calendar);
    lv_obj_set_width(ui_Calendar, 250);
    lv_obj_set_height(ui_Calendar, 200);
    lv_obj_set_align(ui_Calendar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Calendar, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Calendar, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Calendar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Clock = lv_label_create(ui_Calendar);
    lv_obj_set_width(ui_Clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Clock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clock, "Clock");
    lv_obj_set_style_text_color(ui_Clock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clock, &ui_font_digi40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_Calendar);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "10:37");
    lv_obj_set_style_text_letter_space(ui_Time, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time, &ui_font_digital60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddmmyy = lv_label_create(ui_Calendar);
    lv_obj_set_width(ui_ddmmyy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ddmmyy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ddmmyy, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ddmmyy, "dd   mm   yy");
    lv_obj_set_style_text_color(ui_ddmmyy, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddmmyy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ddmmyy, &ui_font_digi40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DMY = lv_label_create(ui_Calendar);
    lv_obj_set_width(ui_DMY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DMY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DMY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DMY, "20  11  24");
    lv_obj_set_style_text_color(ui_DMY, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DMY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DMY, &ui_font_digital60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Inside = lv_obj_create(ui_info);
    lv_obj_remove_style_all(ui_Inside);
    lv_obj_set_width(ui_Inside, 250);
    lv_obj_set_height(ui_Inside, 133);
    lv_obj_set_align(ui_Inside, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Inside, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Inside, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Inside, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_INhome = lv_img_create(ui_Inside);
    lv_img_set_src(ui_INhome, &ui_img_home_png);
    lv_obj_set_width(ui_INhome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_INhome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_INhome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_INhome, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_INhome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_INhome, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_INhome, lv_color_hex(0x001AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_INhome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp1 = lv_label_create(ui_Inside);
    lv_obj_set_width(ui_Temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp1, "27 *c");
    lv_obj_set_style_text_color(ui_Temp1, lv_color_hex(0x001AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp1, &ui_font_digital60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humid1 = lv_label_create(ui_Inside);
    lv_obj_set_width(ui_Humid1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humid1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Humid1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humid1, "50 %");
    lv_obj_set_style_text_color(ui_Humid1, lv_color_hex(0x001AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humid1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humid1, &ui_font_digital60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather = lv_obj_create(ui_info);
    lv_obj_remove_style_all(ui_Weather);
    lv_obj_set_width(ui_Weather, 250);
    lv_obj_set_height(ui_Weather, 200);
    lv_obj_set_align(ui_Weather, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Weather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Weather, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Weather, lv_color_hex(0x00C5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Weather, lv_color_hex(0x6FFFDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Weather, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Weather, &ui_img_clouds_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Moonphase = lv_obj_create(ui_info);
    lv_obj_remove_style_all(ui_Moonphase);
    lv_obj_set_width(ui_Moonphase, 250);
    lv_obj_set_height(ui_Moonphase, 177);
    lv_obj_set_align(ui_Moonphase, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Moonphase, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Moonphase, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_Moonphase, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_moon = lv_img_create(ui_Moonphase);
    lv_img_set_src(ui_moon, &ui_img_moon_png);
    lv_obj_set_width(ui_moon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_moon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_moon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_moon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_moon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_state = lv_label_create(ui_Moonphase);
    lv_obj_set_width(ui_state, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_state, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_state, LV_ALIGN_CENTER);
    lv_label_set_text(ui_state, "MOONPHASE");
    lv_obj_set_style_text_color(ui_state, lv_color_hex(0xFFDE62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_state, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_state, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rain_meter = lv_obj_create(ui_info);
    lv_obj_remove_style_all(ui_rain_meter);
    lv_obj_set_width(ui_rain_meter, 250);
    lv_obj_set_height(ui_rain_meter, 200);
    lv_obj_set_align(ui_rain_meter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rain_meter, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_rain_meter, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_rain_meter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Rain = lv_label_create(ui_rain_meter);
    lv_obj_set_width(ui_Rain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Rain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Rain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Rain, "RAIN: 20.5 mm");
    lv_obj_set_style_text_color(ui_Rain, lv_color_hex(0x5557FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Rain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Rain, &ui_font_digi40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_rain_meter);
    lv_obj_set_width(ui_Chart1, 200);
    lv_obj_set_height(ui_Chart1, 100);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart1, 5);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 5);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_Chart1, 0, 0);
    lv_chart_set_zoom_x(ui_Chart1, 250);
    lv_chart_set_zoom_y(ui_Chart1, 1);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 0, 0, 5, 1, true, 60);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 5, 1, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 1, 1, false, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFF9E00),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 1, 2, 3, 4, 5 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);



    ui_Outside = lv_obj_create(ui_info);
    lv_obj_remove_style_all(ui_Outside);
    lv_obj_set_width(ui_Outside, 250);
    lv_obj_set_height(ui_Outside, 133);
    lv_obj_set_align(ui_Outside, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Outside, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Outside, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Outside, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OUThome = lv_img_create(ui_Outside);
    lv_img_set_src(ui_OUThome, &ui_img_home_png);
    lv_obj_set_width(ui_OUThome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OUThome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OUThome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OUThome, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OUThome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_OUThome, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OUThome, lv_color_hex(0x00EC0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OUThome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp2 = lv_label_create(ui_Outside);
    lv_obj_set_width(ui_Temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Temp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp2, "27 *c");
    lv_obj_set_style_text_color(ui_Temp2, lv_color_hex(0x00EC0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp2, &ui_font_digital60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humid2 = lv_label_create(ui_Outside);
    lv_obj_set_width(ui_Humid2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humid2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Humid2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humid2, "50 %");
    lv_obj_set_style_text_color(ui_Humid2, lv_color_hex(0x00EC0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humid2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humid2, &ui_font_digital60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_line = lv_slider_create(ui_info);
    lv_slider_set_value(ui_line, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_line) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_line, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_line, 780);
    lv_obj_set_height(ui_line, 5);
    lv_obj_set_x(ui_line, 0);
    lv_obj_set_y(ui_line, 20);
    lv_obj_set_align(ui_line, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_line, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_line, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_line, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_line, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_info, ui_event_info, LV_EVENT_ALL, NULL);

}
