// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Light3_screen_init(void)
{
    ui_Light3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Light3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Light3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Light3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Light3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light31 = lv_obj_create(ui_Light3);
    lv_obj_remove_style_all(ui_light31);
    lv_obj_set_width(ui_light31, 790);
    lv_obj_set_height(ui_light31, 100);
    lv_obj_set_x(ui_light31, 20);
    lv_obj_set_y(ui_light31, -85);
    lv_obj_set_align(ui_light31, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_light31, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_light31, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_light31, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_light31, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_light31, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_light31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mau3 = lv_label_create(ui_light31);
    lv_obj_set_width(ui_mau3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mau3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mau3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mau3, "Color");
    lv_obj_set_style_text_font(ui_mau3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mau31 = lv_slider_create(ui_light31);
    lv_slider_set_value(ui_mau31, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_mau31) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_mau31, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_mau31, 700);
    lv_obj_set_height(ui_mau31, 15);
    lv_obj_set_align(ui_mau31, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_mau31, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mau31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_mau31, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mau31, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_mau31, lv_color_hex(0xFFA200), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_mau31, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_mau31, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mau31, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_light32 = lv_obj_create(ui_Light3);
    lv_obj_remove_style_all(ui_light32);
    lv_obj_set_width(ui_light32, 790);
    lv_obj_set_height(ui_light32, 100);
    lv_obj_set_x(ui_light32, 20);
    lv_obj_set_y(ui_light32, -85);
    lv_obj_set_align(ui_light32, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_light32, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_light32, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_light32, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_light32, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_light32, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_light32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dosang3 = lv_label_create(ui_light32);
    lv_obj_set_width(ui_dosang3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dosang3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dosang3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dosang3, "Brightness");
    lv_obj_set_style_text_font(ui_dosang3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dosang31 = lv_slider_create(ui_light32);
    lv_slider_set_value(ui_dosang31, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_dosang31) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_dosang31, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_dosang31, 700);
    lv_obj_set_height(ui_dosang31, 15);
    lv_obj_set_align(ui_dosang31, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_dosang31, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dosang31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_dosang31, lv_color_hex(0x2F2F2F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dosang31, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_dosang31, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_dosang31, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_dosang31, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dosang31, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dosang31, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mau31, ui_event_mau31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dosang31, ui_event_dosang31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Light3, ui_event_Light3, LV_EVENT_ALL, NULL);

}
