// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Light1_screen_init(void)
{
    ui_Light1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Light1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Light1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Light1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Light1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light11 = lv_obj_create(ui_Light1);
    lv_obj_remove_style_all(ui_light11);
    lv_obj_set_width(ui_light11, 790);
    lv_obj_set_height(ui_light11, 100);
    lv_obj_set_x(ui_light11, 20);
    lv_obj_set_y(ui_light11, -85);
    lv_obj_set_align(ui_light11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_light11, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_light11, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_light11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_light11, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_light11, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_light11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mau1 = lv_label_create(ui_light11);
    lv_obj_set_width(ui_mau1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mau1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mau1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mau1, "Color");
    lv_obj_set_style_text_font(ui_mau1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mau11 = lv_slider_create(ui_light11);
    lv_slider_set_value(ui_mau11, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_mau11) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_mau11, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_mau11, 700);
    lv_obj_set_height(ui_mau11, 15);
    lv_obj_set_align(ui_mau11, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_mau11, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mau11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_mau11, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mau11, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_mau11, lv_color_hex(0xFFA200), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_mau11, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_mau11, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mau11, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_light12 = lv_obj_create(ui_Light1);
    lv_obj_remove_style_all(ui_light12);
    lv_obj_set_width(ui_light12, 790);
    lv_obj_set_height(ui_light12, 100);
    lv_obj_set_x(ui_light12, 20);
    lv_obj_set_y(ui_light12, -85);
    lv_obj_set_align(ui_light12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_light12, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_light12, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_light12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_light12, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_light12, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_light12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dosang1 = lv_label_create(ui_light12);
    lv_obj_set_width(ui_dosang1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dosang1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dosang1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dosang1, "Brightness");
    lv_obj_set_style_text_font(ui_dosang1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dosang11 = lv_slider_create(ui_light12);
    lv_slider_set_value(ui_dosang11, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_dosang11) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_dosang11, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_dosang11, 700);
    lv_obj_set_height(ui_dosang11, 15);
    lv_obj_set_align(ui_dosang11, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_dosang11, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dosang11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_dosang11, lv_color_hex(0x2F2F2F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dosang11, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_dosang11, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_dosang11, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_dosang11, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dosang11, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dosang11, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mau11, ui_event_mau11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dosang11, ui_event_dosang11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Light1, ui_event_Light1, LV_EVENT_ALL, NULL);

}
