// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Light2_screen_init(void)
{
    ui_Light2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Light2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Light2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Light2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Light2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light21 = lv_obj_create(ui_Light2);
    lv_obj_remove_style_all(ui_light21);
    lv_obj_set_width(ui_light21, 790);
    lv_obj_set_height(ui_light21, 100);
    lv_obj_set_x(ui_light21, 20);
    lv_obj_set_y(ui_light21, -85);
    lv_obj_set_align(ui_light21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_light21, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_light21, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_light21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_light21, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_light21, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_light21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mau2 = lv_label_create(ui_light21);
    lv_obj_set_width(ui_mau2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mau2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mau2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mau2, "Color");
    lv_obj_set_style_text_font(ui_mau2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mau21 = lv_slider_create(ui_light21);
    lv_slider_set_value(ui_mau21, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_mau21) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_mau21, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_mau21, 700);
    lv_obj_set_height(ui_mau21, 15);
    lv_obj_set_align(ui_mau21, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_mau21, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mau21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_mau21, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mau21, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_mau21, lv_color_hex(0xFFA200), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_mau21, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_mau21, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mau21, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_light22 = lv_obj_create(ui_Light2);
    lv_obj_remove_style_all(ui_light22);
    lv_obj_set_width(ui_light22, 790);
    lv_obj_set_height(ui_light22, 100);
    lv_obj_set_x(ui_light22, 20);
    lv_obj_set_y(ui_light22, -85);
    lv_obj_set_align(ui_light22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_light22, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_light22, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_light22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_light22, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_light22, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_light22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dosang2 = lv_label_create(ui_light22);
    lv_obj_set_width(ui_dosang2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dosang2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dosang2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dosang2, "Brightness");
    lv_obj_set_style_text_font(ui_dosang2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dosang21 = lv_slider_create(ui_light22);
    lv_slider_set_value(ui_dosang21, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_dosang21) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_dosang21, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_dosang21, 700);
    lv_obj_set_height(ui_dosang21, 15);
    lv_obj_set_align(ui_dosang21, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_dosang21, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dosang21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_dosang21, lv_color_hex(0x2F2F2F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dosang21, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_dosang21, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_dosang21, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_dosang21, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dosang21, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dosang21, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mau21, ui_event_mau21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dosang21, ui_event_dosang21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Light2, ui_event_Light2, LV_EVENT_ALL, NULL);

}
