// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_rgb1_screen_init(void)
{
    ui_rgb1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_rgb1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_rgb1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_rgb1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_set_style_bg_color(ui_rgb1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rgb1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGB11 = lv_obj_create(ui_rgb1);
    lv_obj_remove_style_all(ui_RGB11);
    lv_obj_set_width(ui_RGB11, 274);
    lv_obj_set_height(ui_RGB11, 300);
    lv_obj_set_x(ui_RGB11, -32);
    lv_obj_set_y(ui_RGB11, 33);
    lv_obj_set_align(ui_RGB11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RGB11, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_RGB11, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RGB11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RGB11, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RGB11, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGB11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel1 = lv_colorwheel_create(ui_RGB11, true);
    lv_colorwheel_set_mode_fixed(ui_Colorwheel1, true);
    lv_obj_set_width(ui_Colorwheel1, 150);
    lv_obj_set_height(ui_Colorwheel1, 150);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Colorwheel1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Colorwheel1, LV_DIR_TOP);

    ui_rgbcolor1 = lv_label_create(ui_RGB11);
    lv_obj_set_width(ui_rgbcolor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rgbcolor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rgbcolor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rgbcolor1, "Color");
    lv_obj_set_style_text_color(ui_rgbcolor1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rgbcolor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rgbcolor1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGB12 = lv_obj_create(ui_rgb1);
    lv_obj_remove_style_all(ui_RGB12);
    lv_obj_set_width(ui_RGB12, 274);
    lv_obj_set_height(ui_RGB12, 300);
    lv_obj_set_x(ui_RGB12, -32);
    lv_obj_set_y(ui_RGB12, 33);
    lv_obj_set_align(ui_RGB12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RGB12, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_RGB12, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RGB12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RGB12, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RGB12, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGB12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RGB12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brightness1 = lv_arc_create(ui_RGB12);
    lv_obj_set_width(ui_Brightness1, 150);
    lv_obj_set_height(ui_Brightness1, 150);
    lv_obj_set_x(ui_Brightness1, -16);
    lv_obj_set_y(ui_Brightness1, -143);
    lv_obj_set_align(ui_Brightness1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Brightness1, 50);
    lv_obj_set_style_arc_color(ui_Brightness1, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Brightness1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Brightness1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Brightness1, lv_color_hex(0x00ACFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Brightness1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Brightness1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Brightness1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Brightness1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_rgbbrightness1 = lv_label_create(ui_RGB12);
    lv_obj_set_width(ui_rgbbrightness1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rgbbrightness1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rgbbrightness1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rgbbrightness1, "Brightness");
    lv_obj_set_style_text_color(ui_rgbbrightness1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rgbbrightness1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rgbbrightness1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Colorwheel1, ui_event_Colorwheel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Brightness1, ui_event_Brightness1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rgb1, ui_event_rgb1, LV_EVENT_ALL, NULL);

}
