// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_rgb2_screen_init(void)
{
    ui_rgb2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_rgb2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_rgb2, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_rgb2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_set_style_bg_color(ui_rgb2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rgb2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGB21 = lv_obj_create(ui_rgb2);
    lv_obj_remove_style_all(ui_RGB21);
    lv_obj_set_width(ui_RGB21, 274);
    lv_obj_set_height(ui_RGB21, 300);
    lv_obj_set_x(ui_RGB21, -32);
    lv_obj_set_y(ui_RGB21, 33);
    lv_obj_set_align(ui_RGB21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RGB21, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_RGB21, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RGB21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RGB21, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RGB21, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGB21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel2 = lv_colorwheel_create(ui_RGB21, true);
    lv_colorwheel_set_mode_fixed(ui_Colorwheel2, true);
    lv_obj_set_width(ui_Colorwheel2, 150);
    lv_obj_set_height(ui_Colorwheel2, 150);
    lv_obj_set_align(ui_Colorwheel2, LV_ALIGN_CENTER);

    ui_rgbcolor2 = lv_label_create(ui_RGB21);
    lv_obj_set_width(ui_rgbcolor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rgbcolor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rgbcolor2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rgbcolor2, "Color");
    lv_obj_set_style_text_color(ui_rgbcolor2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rgbcolor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rgbcolor2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGB22 = lv_obj_create(ui_rgb2);
    lv_obj_remove_style_all(ui_RGB22);
    lv_obj_set_width(ui_RGB22, 274);
    lv_obj_set_height(ui_RGB22, 300);
    lv_obj_set_x(ui_RGB22, -32);
    lv_obj_set_y(ui_RGB22, 33);
    lv_obj_set_align(ui_RGB22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RGB22, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_RGB22, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RGB22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RGB22, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RGB22, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGB22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RGB22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brightness2 = lv_arc_create(ui_RGB22);
    lv_obj_set_width(ui_Brightness2, 150);
    lv_obj_set_height(ui_Brightness2, 150);
    lv_obj_set_x(ui_Brightness2, -16);
    lv_obj_set_y(ui_Brightness2, -143);
    lv_obj_set_align(ui_Brightness2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Brightness2, 50);
    lv_obj_set_style_arc_color(ui_Brightness2, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Brightness2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Brightness2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Brightness2, lv_color_hex(0x00ACFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Brightness2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Brightness2, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Brightness2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Brightness2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_rgbbrightness2 = lv_label_create(ui_RGB22);
    lv_obj_set_width(ui_rgbbrightness2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rgbbrightness2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rgbbrightness2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rgbbrightness2, "Brightness");
    lv_obj_set_style_text_color(ui_rgbbrightness2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rgbbrightness2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rgbbrightness2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Colorwheel2, ui_event_Colorwheel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Brightness2, ui_event_Brightness2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rgb2, ui_event_rgb2, LV_EVENT_ALL, NULL);

}
